insert into public.permissions (flag, name, group_name, description, is_system)
values
  ('core.system', 'System access', 'Core', 'Access system-level CMS features.', true),
  ('core.appearance', 'Appearance access', 'Core', 'Access appearance and navigation features.', true),
  ('settings.index', 'View settings', 'Settings', 'View CMS settings.', true),
  ('settings.general', 'Manage general settings', 'Settings', 'Manage general site settings.', true),
  ('users.index', 'View users', 'Users', 'View CMS users.', true),
  ('users.create', 'Create users', 'Users', 'Create CMS users.', true),
  ('users.edit', 'Edit users', 'Users', 'Edit CMS users.', true),
  ('users.delete', 'Delete users', 'Users', 'Delete CMS users.', true),
  ('roles.index', 'View roles', 'Roles', 'View CMS roles.', true),
  ('roles.create', 'Create roles', 'Roles', 'Create CMS roles.', true),
  ('roles.edit', 'Edit roles', 'Roles', 'Edit CMS roles and assigned permissions.', true),
  ('roles.delete', 'Delete roles', 'Roles', 'Delete CMS roles.', true),
  ('permissions.index', 'View permissions', 'Permissions', 'View permission catalog.', true),
  ('media.index', 'View media', 'Media', 'View media library.', true),
  ('media.upload', 'Upload media', 'Media', 'Upload media files.', true),
  ('media.edit', 'Edit media', 'Media', 'Edit media metadata.', true),
  ('media.delete', 'Delete media', 'Media', 'Delete media files.', true),
  ('media-folders.create', 'Create media folders', 'Media folders', 'Create media folders.', true),
  ('media-folders.edit', 'Edit media folders', 'Media folders', 'Edit media folders.', true),
  ('media-folders.delete', 'Delete media folders', 'Media folders', 'Delete media folders.', true),
  ('pages.index', 'View pages', 'Pages', 'View CMS pages.', true),
  ('pages.create', 'Create pages', 'Pages', 'Create CMS pages.', true),
  ('pages.edit', 'Edit pages', 'Pages', 'Edit CMS pages.', true),
  ('pages.delete', 'Delete pages', 'Pages', 'Delete CMS pages.', true),
  ('pages.publish', 'Publish pages', 'Pages', 'Publish and schedule CMS pages.', true),
  ('blog.index', 'View blog', 'Blog', 'Access blog management.', true),
  ('blog-posts.index', 'View blog posts', 'Blog posts', 'View blog posts.', true),
  ('blog-posts.create', 'Create blog posts', 'Blog posts', 'Create blog posts.', true),
  ('blog-posts.edit', 'Edit blog posts', 'Blog posts', 'Edit blog posts.', true),
  ('blog-posts.delete', 'Delete blog posts', 'Blog posts', 'Delete blog posts.', true),
  ('blog-posts.publish', 'Publish blog posts', 'Blog posts', 'Publish and schedule blog posts.', true),
  ('categories.index', 'View categories', 'Categories', 'View blog categories.', true),
  ('categories.create', 'Create categories', 'Categories', 'Create blog categories.', true),
  ('categories.edit', 'Edit categories', 'Categories', 'Edit blog categories.', true),
  ('categories.delete', 'Delete categories', 'Categories', 'Delete blog categories.', true),
  ('tags.index', 'View tags', 'Tags', 'View blog tags.', true),
  ('tags.create', 'Create tags', 'Tags', 'Create blog tags.', true),
  ('tags.edit', 'Edit tags', 'Tags', 'Edit blog tags.', true),
  ('tags.delete', 'Delete tags', 'Tags', 'Delete blog tags.', true),
  ('menus.index', 'View menus', 'Menus', 'View navigation menus.', true),
  ('menus.create', 'Create menus', 'Menus', 'Create navigation menus.', true),
  ('menus.edit', 'Edit menus', 'Menus', 'Edit navigation menus.', true),
  ('menus.delete', 'Delete menus', 'Menus', 'Delete navigation menus.', true),
  ('menu-nodes.edit', 'Edit menu nodes', 'Menus', 'Edit menu tree nodes.', true),
  ('seo-meta.edit', 'Edit SEO meta', 'SEO', 'Edit entity SEO metadata.', true),
  ('slugs.edit', 'Edit slugs', 'Slugs', 'Edit entity slugs.', true),
  ('audit-logs.index', 'View audit logs', 'Audit logs', 'View audit logs.', true)
on conflict (flag) do update
set
  name = excluded.name,
  group_name = excluded.group_name,
  description = excluded.description,
  is_system = excluded.is_system,
  updated_at = now();
