export const Permission = {
  CORE_SYSTEM: "core.system",
  CORE_APPEARANCE: "core.appearance",
  SETTINGS_INDEX: "settings.index",
  SETTINGS_GENERAL: "settings.general",
  USERS_INDEX: "users.index",
  USERS_CREATE: "users.create",
  USERS_EDIT: "users.edit",
  USERS_DELETE: "users.delete",
  ROLES_INDEX: "roles.index",
  ROLES_CREATE: "roles.create",
  ROLES_EDIT: "roles.edit",
  ROLES_DELETE: "roles.delete",
  PERMISSIONS_INDEX: "permissions.index",
  MEDIA_INDEX: "media.index",
  MEDIA_UPLOAD: "media.upload",
  MEDIA_EDIT: "media.edit",
  MEDIA_DELETE: "media.delete",
  MEDIA_FOLDERS_CREATE: "media-folders.create",
  MEDIA_FOLDERS_EDIT: "media-folders.edit",
  MEDIA_FOLDERS_DELETE: "media-folders.delete",
  PAGES_INDEX: "pages.index",
  PAGES_CREATE: "pages.create",
  PAGES_EDIT: "pages.edit",
  PAGES_DELETE: "pages.delete",
  PAGES_PUBLISH: "pages.publish",
  BLOG_INDEX: "blog.index",
  BLOG_POSTS_INDEX: "blog-posts.index",
  BLOG_POSTS_CREATE: "blog-posts.create",
  BLOG_POSTS_EDIT: "blog-posts.edit",
  BLOG_POSTS_DELETE: "blog-posts.delete",
  BLOG_POSTS_PUBLISH: "blog-posts.publish",
  CATEGORIES_INDEX: "categories.index",
  CATEGORIES_CREATE: "categories.create",
  CATEGORIES_EDIT: "categories.edit",
  CATEGORIES_DELETE: "categories.delete",
  TAGS_INDEX: "tags.index",
  TAGS_CREATE: "tags.create",
  TAGS_EDIT: "tags.edit",
  TAGS_DELETE: "tags.delete",
  MENUS_INDEX: "menus.index",
  MENUS_CREATE: "menus.create",
  MENUS_EDIT: "menus.edit",
  MENUS_DELETE: "menus.delete",
  MENU_NODES_EDIT: "menu-nodes.edit",
  SEO_META_EDIT: "seo-meta.edit",
  SLUGS_EDIT: "slugs.edit",
  AUDIT_LOGS_INDEX: "audit-logs.index",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const MVP_PERMISSIONS = Object.values(Permission);

